# Estados del pedido
PEDIDO_SOLICITADO = 1
PEDIDO_ACEPTADO = 2
PEDIDO_RECOGIDO = 3
PEDIDO_RECHAZADO = 4
PEDIDO_ENTREGADO = 5
PEDIDO_PAGADO = 6

# Estados del item del pedido
ITEM_SOLICITADO = 1
ITEM_ACEPTADO = 2
ITEM_RECOGIDO = 3
ITEM_RECHAZADO = 4
ITEM_ENTREGADO = 5
ITEM_PAGADO = 6

# estados item_pedido
ITEM_SOLICITADO = 1

# Roles de usuario
ADMIN = 1
PROVEEDOR = 2
RESTAURANTE = 3
OPERARIO = 4